id: "20260208-152802_create-ai-steering-rule-for-career-planning"
title: "Create AI steering rule for career planning"
session_id: "5a2e7f9e-2a71-4474-875c-0670b4eb5b82"
created_at: "2026-02-08T15:28:02+00:00"
status: "ACTIVE"
