id: "20260207-175758_task-completion-notification-acknowledgment"
title: "Task completion notification acknowledgment"
session_id: "3a5a3252-5633-42ea-9654-84ccad000557"
created_at: "2026-02-07T17:57:58+00:00"
status: "ACTIVE"
