id: "20260207-162536_why-in-personalprojectspai-folder"
title: "Why in personal_projects/pai folder"
session_id: "f3ec8f3c-4eb4-4e86-bc78-655421610cab"
created_at: "2026-02-07T16:25:36+00:00"
status: "ACTIVE"
