id: "20260208-131822_career-transition-to-ai-innovation-leadership"
title: "Career transition to AI innovation leadership"
session_id: "bc58f5ec-4fa0-4535-a77a-d0f2a490e5ce"
created_at: "2026-02-08T13:18:22+00:00"
status: "ACTIVE"
