id: "20260208-130157_build-pai-learning-talent-profile-plan"
title: "Build PAI Learning & Talent Profile Plan"
session_id: "78feacf1-ddbf-4b5d-a9a7-bba6f70de48c"
created_at: "2026-02-08T13:01:57+00:00"
status: "ACTIVE"
