id: "20260207-194428_resume-and-complete-frozen-plan-task"
title: "Resume and complete frozen plan task"
session_id: "75566224-87ab-49f7-aa1c-c0bd55fb7ea4"
created_at: "2026-02-07T19:44:28+00:00"
status: "ACTIVE"
