id: "20260207-193552_task-completion-notification-acknowledgment"
title: "Task completion notification acknowledgment"
session_id: "a7b50b8e-23f6-411b-98d0-803425a20928"
created_at: "2026-02-07T19:35:52+00:00"
status: "ACTIVE"
